"""add role to users

Revision ID: 1fe86cf407ef
Revises: d6a7bce5c6fd
Create Date: 2026-06-24 09:20:28.246238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe86cf407ef'
down_revision: Union[str, Sequence[str], None] = 'd6a7bce5c6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE doc_scope AS ENUM ('PERSONAL', 'KNOWLEDGE_BASE')")
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('scope', sa.Enum('PERSONAL', 'KNOWLEDGE_BASE', name='doc_scope'), nullable=False))
    op.add_column('documents', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('mindmap_data', sa.JSON(), nullable=True))
    op.alter_column('documents', 'extracted_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    op.drop_column('documents', 'user_id')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('documents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.alter_column('documents', 'extracted_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'mindmap_data')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'owner_id')
    op.drop_column('documents', 'scope')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'original_filename')
    op.execute("DROP TYPE doc_scope")
    # ### end Alembic commands ###


