"""add whiteboard_data to documents

Revision ID: 6e0a645b8c08
Revises: 982aa75ebd51
Create Date: 2026-06-24 09:43:57.660665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0a645b8c08'
down_revision: Union[str, Sequence[str], None] = '982aa75ebd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('whiteboard_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'whiteboard_data')
    # ### end Alembic commands ###
